### ISSUE TITLE
pyimgur.__init__.User.getalbums() and getImages() returns 400

### ISSUE THREAD

**Issue by hzhou0** [Damgaard/PyImgur#44]
I am trying to access all albums from my authenticated user as below(python=2.7). Other pyimgur.User methods such as get_statistics() ran without issue. 

```
import pyimgur

CLIENT_ID = "**********"
CLIENT_SECRET = "****************"  

im = pyimgur.Imgur(CLIENT_ID, CLIENT_SECRET, refresh_token="***********")
im.refresh_access_token()
#album=im.create_album("An authorized album", "Cool stuff!")
user=im.get_user("************")
print(user)
print(user.get_images())


Traceback (most recent call last):
  File "main.py", line 15, in <module>
    print(user.get_images())  File "/home/runner/.local/share/virtualenvs/python2/lib/python2.7/site-packages/pyimgur/__init__.py", line 1347, in get_images
    resp = self._imgur._send_request(url, limit=limit)  File "/home/runner/.local/share/virtualenvs/python2/lib/python2.7/site-packages/pyimgur/__init__.py", line 731, in _send_request
    result = request.send_request(url, verify=self.verify, **kwargs)  File "/home/runner/.local/share/virtualenvs/python2/lib/python2.7/site-packages/pyimgur/request.py", line 102, in send_request
    resp.raise_for_status()  File "/home/runner/.local/share/virtualenvs/python2/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.imgur.com/3/account/NeverLucky135/images/%7B%7D

```

**Comment by furas** [comment]
There is bug in `_send_request()` in [line 728](https://github.com/Damgaard/PyImgur/blob/master/pyimgur/__init__.py#L728)

It should be 

    url = base_url.format(page)

instead of 

    url.format(page)
